# Generated by Django 4.2.6 on 2023-10-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DangerSensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('temperaturу', models.FloatField()),
                ('humidity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeSensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('temperaturу', models.FloatField()),
                ('humidity', models.FloatField()),
            ],
        ),
    ]
